flags: {}
extra-package-dbs: []
packages:
- '.'
- location:  
      git: https://github.com/andrewufrank/uniform-strings.git
      commit:  ba8bd37567758c1807bf470b3dda4f471cee0f5f
      extra-dep: true
- location:  
      git: https://github.com/andrewufrank/uniform-error.git
      commit:  46c62fcf8b4d6b7a5a9a3622c724ab573fce295d
      extra-dep: true 
- location:  
      git: https://github.com/andrewufrank/uniform-algebra.git
      commit:  f218936ca2db8b711092f1a6b08aa081114e811a
      extra-dep: true 
- location:  
      git: https://github.com/andrewufrank/uniform-time.git
      commit:  cf8aa3c54e6538a4c4d1b1d4c4b59e0efac2fbb3
      extra-dep: true 
- location: 
        git: https://github.com/andrewufrank/uniform-fileio/
        commit: 1623818af694c08e97d2a6fe4492bda8af539ad7
- location: 
        git: https://github.com/andrewufrank/uniform-convenience/
        commit:  72bde15e26a2bd988d95e2826c1c3164a0fbe542
extra-deps:
- data-easy-0.7.0
- test-invariant-0.4.5.0
resolver: lts-8.12
